### GET request para buscar todas as metas
GET http://localhost:3333/goals?limit=4&page=1
Content-Type: application/json

### GET request para buscar todas as metas completadas na semana
GET http://localhost:3333/pending-goals
Content-Type: application/json

### POST request para criar uma nova meta
POST http://localhost:3333/goals
Content-Type: application/json

{
  "title": "Exercitar",
  "desiredWeeklyFrequency": 3
}

### POST request para completar uma meta
POST http://localhost:3333/goal-completions
Content-Type: application/json

{
  "goalId": "djpvshay60zimb4hjcdyq9ri"
}

### POST request para descompletar uma meta
POST http://localhost:3333/undo-goal-completions
Content-Type: application/json

{
  "goalCompletionId": "auyvwsb6sto20izjkrksfzmf"
}

### GET request para buscar ...
GET http://localhost:3333/week-summary
Content-Type: application/json